import Head from "next/head";
import { useEffect, useState } from "react";
import { getContract } from "../../configureWarpClient";
import { Inter } from "next/font/google";
import ReactMarkdown from "react-markdown";

const inter = Inter({ subsets: ["latin"] });

type Post = {
  title: string;
  content: string;
  id: string;
};

export default function Home() {
  const [posts, setPosts] = useState<Post[]>([]);
  useEffect(() => {
    readState();
  }, []);
  async function readState() {
    const contract = await getContract();
    try {
      const data = await contract.readState();
      console.log("data: ", data);
      // @ts-ignore
      const posts: Post[] = Object.values(data.cachedValue.state.posts);
      setPosts(posts);
      console.log("posts: ", posts);
    } catch (err) {
      console.log("error: ", err);
    }
  }

  return (
    <>
      <Head>
        <title>PermaBlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={containerStyle}>
        <h1 style={headingStyle}>PermaBlog</h1>
        {posts.map((post, index) => (
          <div key={index} style={postStyle}>
            <p style={titleStyle}>{post.title}</p>
            <ReactMarkdown>{post.content}</ReactMarkdown>
          </div>
        ))}
      </div>
    </>
  );
}

const containerStyle = {
  width: "900px",
  margin: "0 auto"
};

const headingStyle = {
  fontSize: "64px"
};
const postStyle = {
  padding: "15px 0px 0px",
  borderBottom: "1px solid rgba(255, 255, 255, .2)"
};

const titleStyle = {
  fontSize: "34px",
  marginBottom: "0px"
};
